<a href="https://colab.research.google.com/github/henryberroa4040/python-basico/blob/main/Clase-7-Script02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modulo Numpy

In [ ]:
# Carguemos el modulo numpy
import numpy as np

In [ ]:
# Documentacion del modulo
help(np)

In [ ]:
# Numpy provee una serie de submodulos/subpaquetes

# random
#         Core Random Tools
#     linalg
#         Core Linear Algebra Tools
#     fft
#         Core FFT routines
#     polynomial
#         Polynomial tools

In [ ]:
# Elementos que compones al modulo numpy
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [ ]:
# Elemento que componen al modulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [ ]:
# Documentacion del modulo random
help(np.random)

In [ ]:
# Documentacion de la funcion triangular del submodulo random de modulo numpy
help(np.random.triangular)

In [ ]:
# unidimensional
v1 = np.random.triangular(12,14,16,10)
v1

array([15.26059908, 15.1286136 , 15.62721203, 12.63980754, 15.81496672,
       14.32040678, 13.25052411, 14.73762619, 12.79861448, 13.7202856 ])

In [ ]:
# vidimensional
v2 = np.random.triangular(12,14,16,(3,4))
v2

array([[13.57412619, 14.5530935 , 14.22675903, 13.66286304],
       [14.04886677, 14.67401782, 14.50060605, 12.95309503],
       [12.68240761, 12.92422238, 14.63287703, 13.6636691 ]])

In [ ]:
# tridimencional
v3 = np.random.triangular(12,14,16,(2,3,4))
v3

array([[[14.32576804, 14.16430639, 13.02949442, 13.04424113],
        [13.40091703, 12.24855603, 13.60067563, 12.52801252],
        [13.98540049, 13.57190787, 15.58459568, 13.60420619]],

       [[14.00213456, 14.12194841, 13.97621137, 14.99079476],
        [15.08112061, 13.762334  , 13.6122984 , 14.85216949],
        [13.57264247, 14.77008311, 12.3394869 , 12.22397255]]])

In [ ]:
# Atepenultima componente del objeto unidimensional v1
v1[-3]

np.float64(14.737626190149902)

In [ ]:
# Accedamos a elementos del objeto bidimensional v2

In [ ]:
# Tercera columna de v2  # Primera dimension filas y segunda columna
v2[:,2]

array([14.22675903, 14.50060605, 14.63287703])

In [ ]:
# Tercera fila de v2
v2[2,:]

array([12.68240761, 12.92422238, 14.63287703, 13.6636691 ])

In [ ]:
# Mostremos la primer y ultima columna de v2
v2[:,(0,-1)]    # El profesor lo agrupa en una tupla, pero veo que también se puede con una lista.

array([[13.57412619, 13.66286304],
       [14.04886677, 12.95309503],
       [12.68240761, 13.6636691 ]])

In [ ]:
# Accedamos a elementos de un objeto tridimensional  # La primera dimesion define si el el grupo de arriba o abajo
v3[0,(1,2),1]

array([12.24855603, 13.57190787])

In [ ]:
# tipo de dato
type(v1)

numpy.ndarray

In [ ]:
# tipo de dato
type(v2)

numpy.ndarray

In [ ]:
# tipo de dato
type(v3)

numpy.ndarray

In [ ]:
# Acceso de los meotodos de un dato de tipo ndarray de numpy
dir(v3)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '_